# Generated by Django 5.0.6 on 2024-06-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uapaterno', models.CharField(max_length=15)),
                ('uapmaterno', models.CharField(max_length=15)),
                ('unombre', models.CharField(max_length=30)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.PositiveIntegerField(max_length=10)),
                ('colonia', models.CharField(max_length=60)),
                ('cp', models.PositiveIntegerField(max_length=5)),
                ('email', models.EmailField(max_length=50)),
                ('localidad', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('sapaterno', models.CharField(max_length=15)),
                ('sapmaterno', models.CharField(max_length=15)),
                ('snombre', models.CharField(max_length=15)),
                ('cargo', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
