# Generated by Django 5.0.6 on 2024-07-02 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_servidor_usuario_remove_formulario_calle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='servidor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='formulario.servidor'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='formulario.usuario'),
        ),
    ]
