# Generated by Django 5.0.6 on 2024-07-02 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_alter_formulario_servidor_alter_formulario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.servidor'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.usuario'),
        ),
    ]
