# Generated by Django 5.0.6 on 2024-07-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_alter_formulario_servidor_alter_formulario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='servidor',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='formulario',
            name='calle',
            field=models.CharField(default='Sin calle especificada', max_length=50),
        ),
        migrations.AddField(
            model_name='formulario',
            name='cargo',
            field=models.CharField(default='Sin cargo especificado', max_length=80),
        ),
        migrations.AddField(
            model_name='formulario',
            name='colonia',
            field=models.CharField(default='Sin colonia especificada', max_length=60),
        ),
        migrations.AddField(
            model_name='formulario',
            name='cp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formulario',
            name='email',
            field=models.EmailField(default='Sin colonia especificada', max_length=50),
        ),
        migrations.AddField(
            model_name='formulario',
            name='estado',
            field=models.CharField(default='Sin estado especificado', max_length=20),
        ),
        migrations.AddField(
            model_name='formulario',
            name='localidad',
            field=models.CharField(default='Sin localidad especificada', max_length=20),
        ),
        migrations.AddField(
            model_name='formulario',
            name='municipio',
            field=models.CharField(default='Sin municipio especificado', max_length=20),
        ),
        migrations.AddField(
            model_name='formulario',
            name='numero',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formulario',
            name='sapaterno',
            field=models.CharField(default='No especificado', max_length=15),
        ),
        migrations.AddField(
            model_name='formulario',
            name='sapmaterno',
            field=models.CharField(default='No especificado', max_length=15),
        ),
        migrations.AddField(
            model_name='formulario',
            name='snombre',
            field=models.CharField(default='No especificado', max_length=15),
        ),
        migrations.AddField(
            model_name='formulario',
            name='uapaterno',
            field=models.CharField(default='No especificado', max_length=15),
        ),
        migrations.AddField(
            model_name='formulario',
            name='uapmaterno',
            field=models.CharField(default='No especificado', max_length=15),
        ),
        migrations.AddField(
            model_name='formulario',
            name='unombre',
            field=models.CharField(default='No especificado', max_length=30),
        ),
        migrations.DeleteModel(
            name='Servidor',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
