# Generated by Django 5.0.6 on 2024-07-02 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_remove_formulario_servidor_remove_formulario_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapaterno', models.CharField(max_length=15)),
                ('sapmaterno', models.CharField(max_length=15)),
                ('snombre', models.CharField(max_length=15)),
                ('cargo', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uapaterno', models.CharField(max_length=15)),
                ('uapmaterno', models.CharField(max_length=15)),
                ('unombre', models.CharField(max_length=30)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.PositiveIntegerField()),
                ('colonia', models.CharField(max_length=60)),
                ('cp', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('localidad', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='sapaterno',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='sapmaterno',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='snombre',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='uapaterno',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='uapmaterno',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='unombre',
        ),
        migrations.AddField(
            model_name='formulario',
            name='servidor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='formulario.servidor'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='formulario.usuario'),
        ),
    ]
