# Generated by Django 5.0.6 on 2024-07-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0007_usuario_last_login_usuario_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
    ]
