# Generated by Django 5.0.6 on 2024-07-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0008_remove_usuario_last_login_remove_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
