# Generated by Django 5.0.6 on 2024-07-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0010_perfil_remove_usuario_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default=None, max_length=60),
        ),
    ]
