# Generated by Django 5.0.6 on 2024-07-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0011_delete_perfil_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
