# Generated by Django 5.0.6 on 2024-07-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0012_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
