# Generated by Django 5.0.6 on 2024-07-10 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0013_validationtoken_delete_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
    ]
