# Generated by Django 5.0.6 on 2024-07-10 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0014_remove_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='validacion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='formulario.validationtoken'),
        ),
    ]
