# Generated by Django 5.0.6 on 2024-07-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0015_formulario_validacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='validacion',
        ),
        migrations.DeleteModel(
            name='ValidationToken',
        ),
    ]
