# Generated by Django 5.0.6 on 2024-07-21 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0017_validationtoken_formulario_validacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='validacion',
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.email')),
            ],
        ),
        migrations.AddField(
            model_name='formulario',
            name='token',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='formulario.token'),
        ),
        migrations.DeleteModel(
            name='ValidationToken',
        ),
    ]
