# Generated by Django 5.0.6 on 2024-07-22 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0019_validationtoken_remove_token_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='validacion',
        ),
        migrations.CreateModel(
            name='TokenEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('is_validated', models.BooleanField(default=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.emailentrada')),
            ],
        ),
        migrations.AddField(
            model_name='formulario',
            name='token',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='formulario.tokenentrada'),
        ),
        migrations.DeleteModel(
            name='ValidationToken',
        ),
    ]
