# Generated by Django 5.0.6 on 2024-07-23 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0022_emailentry_remove_formulario_validacion_tokenentry_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailEntry',
            new_name='Email',
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('is_validated', models.BooleanField(default=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.email')),
            ],
        ),
        migrations.AlterField(
            model_name='formulario',
            name='token',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='formulario.token'),
        ),
        migrations.DeleteModel(
            name='TokenEntry',
        ),
    ]
