# Generated by Django 5.0.6 on 2024-07-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0023_rename_emailentry_email_token_alter_formulario_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
