# Generated by Django 5.0.6 on 2024-07-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0024_formulario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
