# Generated by Django 5.0.6 on 2024-07-31 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0026_alter_formulario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='email',
        ),
    ]
