# Generated by Django 5.0.6 on 2024-07-31 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0027_remove_formulario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='token',
        ),
    ]
