# Generated by Django 5.0.6 on 2024-07-31 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0036_remove_formulario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='email',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='formulario.email'),
        ),
    ]
