# Generated by Django 5.0.6 on 2024-07-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0040_remove_formulario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
