# Generated by Django 5.0.6 on 2024-08-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0042_remove_formulario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
