# Generated by Django 5.0.6 on 2024-08-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0048_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='status',
            field=models.CharField(default='sin responder', max_length=20),
        ),
    ]
