# Generated by Django 5.0.6 on 2024-08-17 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0049_formulario_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='status',
        ),
    ]
