# Generated by Django 5.0.6 on 2024-08-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0050_remove_formulario_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='defaul@example.com', max_length=254),
        ),
    ]
