# Generated by Django 5.0.6 on 2024-08-22 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0053_formulario_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='mensajes/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='formulario.formulario')),
            ],
        ),
    ]
