# Generated by Django 5.0.6 on 2024-08-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0054_mensajeenviado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MensajeEnviado',
            new_name='Mensajes',
        ),
    ]
