# Generated by Django 5.0.6 on 2024-08-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0057_mensajeenviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeenviado',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
